<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        GridLayout:
            cols: 2

            MenuScreen:
            MenuScreen:
        
        GridLayout:
            cols: 1

            SettingsScreen:

<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Goto settings'

<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'My settings button'