<ScreenOne>:
    FloatLayout:
        size: root.width, root.height

        BoxLayout:
            id: customer_component
            padding: 4
            pos_hint: {'x':0, 'y':0}
            size_hint: 1, 1.2
            CustomerCamera:
        
        BoxLayout:
            id: ads_component
            AdsCarousel:
                padding:5
                pos_hint: {'x':0, 'y':0}
                size_hint: 1, 0.47

<ScreenTwo>:
    FloatLayout:
